version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro-learning-platform
    ports:
      - "3000:3000"
    volumes:
      - /node_modules
